name: "CRB"
iso_codes: ["TTO", "BLZ", "BRB", "LCA", "VCT", "GRD", "DMA", "ATG", "KNA"]
embed_model: "dinov2_vits14"

test_size: 0.2
image_size: 560
model: 'SVC'
model_params:
    kernel: ['linear', 'poly', 'rbf', 'sigmoid']
    gamma: [1, 0.1, 0.01, 0.001, 0.0001]
    C: [0.001, 0.01, 0.1, 1.0, 10]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "GridSearchCV"
cv_params:
   cv: 5
   refit: 'f1_score'
   verbose: 1
   n_jobs: -1