embed_model: "dinov2_vitb14"
test_size: 0.2
image_size: 560
model: 'SVC'
model_params:
    kernel: ['sigmoid']
    gamma: [1]
    C: [0.1, 1.0]
selector: 
selector_params:
scalers: ['StandardScaler']
cv: "GridSearchCV"
cv_params:
   cv: 5
   refit: 'f1_score'
   verbose: 1