pos_category: "school"
neg_category: "non_school"
vectors_dir: 'data/vectors/'
rasters_dir: 'data/rasters/'
columns: ['UID', 'source', 'iso', 'country', 'region', 'subregion', 'name', 'geometry', 'giga_id_school']

iso_codes: [
    'ATG', 'AIA', 'YEM', 'SEN', 'BWA', 'MDG', 'BEN', 'BIH', 'BLZ', 'BRB', 
    'CRI', 'DMA', 'GHA', 'GIN', 'GRD', 'HND', 'HUN', 'KAZ', 'KEN', 'KIR', 
    'KNA', 'LCA', 'MNG', 'MSR', 'MWI', 'NAM', 'NER', 'NGA', 'PAN', 'RWA', 
    'SLE', 'SLV', 'SSD', 'THA', 'TTO', 'UKR', 'UZB', 'VCT', 'VGB', 'ZAF', 
    'ZWE', 'BRA'
]

# Data cleaning
proximity: 50
filter_buffer_size: 150
sample_spacing: 300
object_proximity: 300
name_match_threshold: 85
name_match_proximity: 300
priority: ["OSM", "OVERTURE", "UNICEF"]