ISO_REGIONAL_CODES: "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv"
OVERTURE_URL: "s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=places/type=*/*"
GEOBOUNDARIES_URL: "https://www.geoboundaries.org/api/current/gbOpen/"
COLUMNS: ['UID', 'source', 'iso', 'country', 'region', 'subregion', 'name', 'geometry']
SCHOOL: {
    amenity: [
        "school",
        "university",
        "college",
        "institute",
        "academy"
    ]
}
NON_SCHOOL: {
    amenity: [
        "fast_food",
        "food_court",
        "cafe",
        "restaurant",
        "pub",
        "bar",
        "bank",
        "clinic",
        "doctors",
        "hospital",
        "pharmacy",
        "dentist",
        "veterinary",
        "arts_centre",
        "cinema",
        "casino",
        "community_centre",
        "conference_centre",
        "events_venue",
        "fuel",
        "exhibition_centre",
        "planetarium",
        "theatre",
        "nightclub",
        "courthouse",
        "fire_station",
        "police",
        "post_office",
        "prison",
        "townhall",
        "crematorium",
        "funeral_hall",
        "internet_cafe",
        "marketplace",
        "place_of_mourning",
        "place_of_worship"
    ],
    building: [
        "commercial",
        "industrial",
        "office",
        "retail",
        "warehouse",
        "church",
        "cathedral",
        "chapel",
        "mosque",
        "temple",
        "synagogue",
        "shrine",
        "supermarket",
        "fire_station",
        "police",
        "prison",
        "hospital",
        "museum",
        "military"
    ],
    craft: [
        "agricultural_engines",
        "atelier",
        "bakery",
        "blacksmith",
        "boatbuilder",
        "brewery",
        "cabinet_maker",
        "carpenter",
        "electronics_repair",
        "distillery",
        "oil_mill"
    ],
    healthcare: [
        "alternative",
        "audiologist",
        "birthing_center",
        "chiropractor",
        "dentist",
        "midwife",
        "occupational_therapist",
        "optometrist",
        "physiotherapist",
        "psychologist",
        "speech_therapist",
        "blood_bank",
        "blood_donation",
        "vaccination_centre"
    ],
    historic: [
        "church",
        "cathedral",
        "castle",
        "mosque",
        "tower"
    ],
    landuse: [
        "commercial",
        "retail",
        "industrial",
        "warehouse",
        "cemetery",
        "religious"
    ],
    leisure: [
        "adult_gaming_centre",
        "amusement_arcade"
    ],
    military: [
        "barracks",
        "base",
        "office"
    ],
    place: [
        "farm",
        "allotments"
    ],
    power: [
        "transformer"
    ],
    public_transport: [
        "station"
    ],
    railway: [
        "station"
    ],
    office: [
        "government"
    ],
    shop: [
        "alcohol",
        "bakery",
        "beverages",
        "brewing_supplies",
        "butcher",
        "cheese",
        "chocolate",
        "coffee",
        "confectionery",
        "convenience",
        "farm",
        "food",
        "general",
        "department_store",
        "kiosk",
        "mall",
        "supermarket",
        "wholesale",
        "beauty",
        "fabric",
        "fashion",
        "doityourself",
        "electronics",
        "garden_centre"
    ],
    tourism: [
        "guest_house",
        "hostel",
        "hotel",
        "motel",
        "museum",
        "chalet",
        "apartment",
        "zoo"
    ]
}