DIGITALGLOBE_URL: "https://evwhs.digitalglobe.com/mapservice/wmsaccess?"
RASTERS_DIR: 'data/rasters/'
VECTORS_DIR: 'data/vectors/'
DIR: '512x512_60cm'
SIZE: 153.6
WIDTH: 512
HEIGHT: 512
SRS: 'EPSG:3857'
STYLES: ''
TRANSPARENT: True
REQUEST: 'GetMap'
FORMAT: 'image/png'
LAYERS: ['DigitalGlobe:Imagery']
EXCEPTIONS: 'application/vnd.ogc.se_xml'
FEATUREPROFILE: 'Most_Aesthetic_Mosaic_Profile'
COVERAGE_CQL_FILTER: 'productType =%27Pan Sharpened Natural Color%27'
COVERAGE_CQL_FILTER: ''